export const PLUGIN_PREFIX = '@triniti/admin-ui/';
const t = id => `${PLUGIN_PREFIX}${id}`;

export const actionTypes = {
  PREFIX: PLUGIN_PREFIX,

  // app theme
  NEW_THEME_REQUESTED: t('NEW_THEME_REQUESTED'),

  // navigations
  CHANGE_ROUTE_REQUESTED: t('CHANGE_ROUTE_REQUESTED'),
  ROUTE_DID_CHANGED: t('ROUTE_DID_CHANGED'),
  CURRENT_SECTION_CHANGED: t('CURRENT_SECTION_CHANGED'),
  MAIN_NAV_TOGGLED: t('MAIN_NAV_TOGGLED'),
  DROPDOWN_TITLE_CLICKED: t('DROPDOWN_TITLE_CLICKED'),
  DROPDOWN_MENU_CLICKED: t('DROPDOWN_MENU_CLICKED'),
  USER_NAV_TOGGLED: t('USER_NAV_TOGGLED'),
  ASIDE_ACTIVE_TAB_CHANGED: t('ASIDE_ACTIVE_TAB_CHANGED'),
  LOGOUT_REQUESTED: t('LOGOUT_REQUESTED'),

  // alerts
  ALERT_SENT: t('ALERT_SENT'),
  ALERT_DISMISSED: t('ALERT_DISMISSED'),
};
